name: YakPro PO

on:
  push:

jobs:
  setup: 
      runs-on: [linux, windows]
      name: Setup
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Drop vendor"
          run: rm -fr vendor
          
        - name: "Compose"
          run: composer install --no-interaction
  PhpCS:
      runs-on: [linux, windows]
      needs: setup
      name: PHP Code Sniffer
      steps:          
        - name: "PHPCs"
          run: vendor/bin/phpcs