name: YakPro PO

on:
  push:

jobs:
  setup: 
      runs-on: self-hosted
      name: Setup
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Drop vendor"
          run: rm -fr vendor
          
        - name: "Compose"
          run: composer install --no-interaction
  PhpCS:
      runs-on: self-hosted
      needs: setup
      name: PHP Code Sniffer
      steps:          
        - name: "Run PHP Code sniffer"
          run: vendor/bin/phpcs
  PhpStan:
      runs-on: self-hosted
      needs: setup
      name: PHP Stan
      steps:          
        - name: "Run PHPStan static analyser"
          run: vendor/bin/phpstan
  Autotest:
      runs-on: self-hosted
      needs: PhpStan
      name: Autotest
      steps:          
        - name: "Run all tests"
          run: vendor/bin/phpunit tests