name: YakPro PO

on:
  push:

jobs:
  setup: 
      runs-on: self-hosted
      name: Setup
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Drop vendor"
          run: rm -fr vendor
          
        - name: "Compose"
          run: composer install --no-interaction
  PhpCS:
      runs-on: self-hosted
      needs: setup
      name: PHP Code Sniffer
      steps:          
        - name: "PHPCs"
          run: vendor/bin/phpcs
  Autotest:
      runs-on: self-hosted
      needs: setup
      name: Autotest
      steps:          
        - name: "phpunit"
          run: vendor/bin/phpunit --testdox tests